project_id = "tlqpqcyngaaysqydgjzm"

[functions.send-contact-email]
verify_jwt = false

[functions.create-booking]
verify_jwt = true

[functions.create-booking-with-payment]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.export-bookings]
verify_jwt = true

[functions.validate-signup]
verify_jwt = false

[functions.resend-confirmation]
verify_jwt = false