// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlqpqcyngaaysqydgjzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRscXBxY3luZ2FheXNxeWRnanptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NzI1MzMsImV4cCI6MjA3MDU0ODUzM30.HYzHvFq_1bcNUZmiQqZB1hB6rDzit-007CwsuG2V7Os";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});